apiVersion: v1
baseDomain: dima.com
controlPlane:
  name: master
  hyperthreading: Disabled  
  replicas: 3
compute:
- name: worker
  hyperthreading: Disabled
  replicas: 3
metadata:
  name: ocp4
networking:
  clusterNetworks:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 172.18.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {} 
fips: false
pullSecret: '{"auths":{"registry.dima.com:5000":{"auth":"cm9vdDpyZWRoYXQ=","email":"me@working.me"}}}'
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCtZ15DSZaYahaw+Qeqvi0FWBmgJ+mlMCSmraObC7jbAICBfBuhHPE8PaY2LsDqNT2quU4BBHoybXIi17IZCEu5pcO76K9tLbiiabMPdT9d+XcAcHaa/mAiXqI4xnl4Iq3BTxRenTl/k/1aSXeErZwNPdkJ5KDioekalJlMewiZTKdt9AR/SNcClKO/lUCOVyHnMY6x+3QAMYzJhq0PDN8e8YFoCfI4FATQkhVvSyY+M/me00BepubMLZNSyt1YOX1v4vK95UmKHar9NOh/lOF2pejRMkBIS1vd+PcCWUjGnG6n1JG8fD/tcf482XDWoz84RpqSq7f44TzoPIsg97XvYkwIh8n3twsRw6shHxxg8xYVcHSUUu2GFeErAJNuuoj4DC65i99qQPX7isiGmUgPT5eDGa6uDyRoK/Pu8svPenoRn3ooz2j7b4+YRbySzcjlbzxIfbyuZuvg0k3PVR7z5OpMYBt6WIc7zdYhYUcMvyPGVusQdKKjD7YkN4MIK5JOI0Mnl62d6wHuyLSXSa45TtOhU+Oc/AOJukiPDqsL4IBFay7wlznWgAGaokV6jJsgP00caCClSn631fdj9narq0q6CtJQBeI83eJfPALfseFGejSQ6+cmdFyT9cPMh3AU7DBzMRGFbAKzjY/0JJnWa+48hxzLKk7Itkn4wSHmhQ== dshtranv@dima-bastion-ocp'
additionalTrustBundle: |
    -----BEGIN CERTIFICATE-----
    MIIGNTCCBB2gAwIBAgIUKWAv5kyKbkgmzdMaZB1oN/4qC+AwDQYJKoZIhvcNAQEL
    BQAwgYwxCzAJBgNVBAYTAlVTMREwDwYDVQQIDAhOZXcgWW9yazERMA8GA1UEBwwI
    TmV3IFlvcmsxDjAMBgNVBAoMBU15T3JnMQ0wCwYDVQQLDARNeU9VMRwwGgYJKoZI
    hvcNAQkBFg1tZUB3b3JraW5nLm1lMRowGAYDVQQDDBFyZWdpc3RyeS5kaW1hLmNv
    bTAeFw0yMzA1MTcwODEzMTZaFw0zMzA1MTQwODEzMTZaMIGMMQswCQYDVQQGEwJV
    UzERMA8GA1UECAwITmV3IFlvcmsxETAPBgNVBAcMCE5ldyBZb3JrMQ4wDAYDVQQK
    DAVNeU9yZzENMAsGA1UECwwETXlPVTEcMBoGCSqGSIb3DQEJARYNbWVAd29ya2lu
    Zy5tZTEaMBgGA1UEAwwRcmVnaXN0cnkuZGltYS5jb20wggIiMA0GCSqGSIb3DQEB
    AQUAA4ICDwAwggIKAoICAQDEM9mAZAKJ+lW77T5GxrkvG5BAYxsxXlesxxZt1nKJ
    9K51UxmvqhYYcjtbYxmvVMubvxKTQnzQnYxrd1q1DGlfyaRAEIt5uTRW79SVpR0o
    6Yix3vpw7sAcZ9a/HkCgsX0IymMFYGrkpUwmWjpp2+hAkjDSgfg2djOJkDm9OdrK
    BD5xYqb5zGQwOKTlOY2TnSomygZkd+2n5hQ+uuRYkZt7Hn1gIuyurUsDv4dmLb91
    nDqNvju+Z5aDNC9cJpydocRiCR/MBD4Rac1ZSdixaimVrii07oWwAE1w1IdcgGOM
    y6hhC9va7ArSjpi6Nxe1LUjNACNcoJLXl2K8JUS8KJnmpGtrhTEmG3iIeeg6bt8I
    x5YxB2eMRat9ID/2DNV/ycNOMPGX4qz+Jvcy3igLOsx0taKMiNeBxnMuI4amyU/1
    LGySJcnPF17puMNCOYRpQDVO1pyA78Iy85NiCmYNl/Ttowgn6p8OV8pCEt1qX76v
    2piUcTe2uyz0MnqIviSC7dEsKe0o0D7l9+AmZf/qNchlL5i5X0Jh0LV7MysEmWie
    rUEVX5pCBlAdJVhVIBbYPYnHfPmWqX2rmng9FTd+VkeoPxv/EQCya+3kYLbWf5NR
    kV7dHpdmN8NpvRTxR7tEYYm9fIe3DBUpORvpE+OR9F0pnUX1Jj8uCZy8e4u9HgNH
    0QIDAQABo4GMMIGJMCYGA1UdEQQfMB2CCHJlZ2lzdHJ5ghFyZWdpc3RyeS5kaW1h
    LmNvbTAdBgNVHQ4EFgQUfgkblpTJBZwUd05+QWTq+m+0M7MwHwYDVR0jBBgwFoAU
    fgkblpTJBZwUd05+QWTq+m+0M7MwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8E
    BAMCAYYwDQYJKoZIhvcNAQELBQADggIBADyAkAgqGz+g5aAcTqgNbhsS6Gz22KAd
    o94lWQzYUkd6luKdEUvrgMc36bib/YKKdTJ4vscjcBRmDOC86LjdufE5joIqRXOs
    228I3b0q/L737P+pILyugTFf2VmHsC0GEriV1MWKgRhForFB5JJCDKvYQvnquMwS
    uzZgPycpjt5omewlaLsW+cVA13teE2ZhnNwsl0cS+Xqx5+fCGmBNgCo4szsKFM8r
    0NpF/LeWTaND+sn64uW5McE+yjGmxrR2Duwhv5ckVd+zDrgOBWdJoyOsRMpQwe5B
    6v+ANXGMabqia93qBOxEJ7HE9zAzkTbuQZjGmrCZ0zOjeYwFwS4xWdihLDqHdMM3
    IX+7WUwSvEGCYxJenBuw6oh38sXN1e6A/DuwWt2trDq7zfyCr8ObOqw0K8UhIGJz
    fLPiIn+21rVv11UoQCRlHuXxRCCuLscPdkpc6DJsYPcka2LOtLAhJRRM2Q/dxY2z
    Kcs5/IViyy5KSmIrIxQA+FOwZGX6ZT9wmbTmARoUcxOC0eon9/kZMbufoQPTGU83
    Il5bzEC2tts4i6z11FJWkQH2MjV5IlNhoMIxFdAUUWuLLfQFO7n7myoNF4Byd5yI
    i3m8J9xD9K8WOzVkEMov1aX1tTElCAomZipgQipwlctLBQlM0NVEM2dyADTDUjDn
    h4TvqPbnuSt5
    -----END CERTIFICATE-----
imageContentSources:
- mirrors:
  - registry.dima.com:5000/ocp/openshift4
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - registry.dima.com:5000/ocp/openshift4
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev

