apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  namespace: openshift-image-registry
spec:
  storageClassName: "local-storage"
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/mnt/data"
  claimRef:
    namespace: openshift-image-registry
    name: image-registry-storage
---   
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-registry-storage
  namespace: openshift-image-registry
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: local-pv
